### ISSUE TITLE
NON-HLOS.bin is different from the one in the full ROM

### ISSUE THREAD

**Issue by ghost** [XiaomiFirmwareUpdaterReleases/firmware_xiaomi_capricorn#1]
Hash:

Your file: `0f791f75fc8c8856fcdbc245432691420892c0527a4a5cdb462bc2d33534ce8e  NON-HLOS.bin`

That same file from the full MIUI ROM: `4dbee5021f0bb667a9cb523781ded6a79a85c444924890c13f12fb1ac1393506  NON-HLOS.bin`

[MIUI full ROM Downloaded from here](http://en.miui.com/download-314.html)

Version: 8.4.19

Why is there a difference between these 2 files?

**Comment by yshalsager** [comment]
@As4fN1v latest file is 8.4.26 China

**Comment by ghost** [comment]
@yshalsager It's still the same there. Why?

**Comment by yshalsager** [comment]
Ask miui :p @As4fN1v 
My scripts just do their job.

**Comment by ghost** [comment]
After some digging (a lot), I found that they are equal.

Line 77 in https://github.com/XiaomiFirmwareUpdater/xiaomi-flashable-firmware-creator/blob/master/create_flashable_firmware.sh causes the hashes to change somehow, while the file still remains the same.
